import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/hooks/use-auth';
import { learningApi } from '@/lib/learning-api';
import { Switch } from './ui/switch';
import { Checkbox } from './ui/checkbox';
import { Input } from './ui/input';
import { Button } from './ui/button';
export default function LearningPreferences(){
  const {user}=useAuth(),query=useQueryClient();const [native,setNative]=useState(user?.preferences?.nativeLanguage||''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  async function save(data:unknown){setBusy(true);try{await learningApi('/api/user/preferences',data,'PATCH');await query.invalidateQueries({queryKey:['/api/user']});setStatus('Preference saved.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
  const known=user?.preferences?.knownLanguages||[];
  return <section className="learning-preferences"><h2>How you prefer to learn</h2><div className="preference-row"><div><label htmlFor="quiet-companion">Minimize companion commentary</label><p>Keep every instruction, hint and correction. The fox stays in the LingoMitra logo.</p></div><Switch id="quiet-companion" checked={Boolean(user?.preferences?.minimizeCompanion)} disabled={busy} onCheckedChange={minimizeCompanion=>void save({minimizeCompanion})}/></div><p><strong>Explanation language: English.</strong> The current lessons are authored in English. Hindi and Telugu explanations would need their own teaching design; they are not available yet.</p><label htmlFor="native-language">Native or first language (optional)</label><div className="guided-actions"><Input id="native-language" value={native} onChange={e=>setNative(e.target.value)} maxLength={60} placeholder="The language you grew up with"/><Button variant="outline" disabled={busy} onClick={()=>void save({nativeLanguage:native})}>Save first language</Button></div><p>Other languages you know (optional). This records context; it does not automatically translate lessons.</p><div className="language-preferences">{[['en','English'],['hi','Hindi'],['te','Telugu'],['kn','Kannada'],['de','German'],['es','Spanish'],['fr','French'],['ja','Japanese'],['zh','Chinese']].map(([code,name])=><label key={code}><Checkbox checked={known.includes(code)} disabled={busy} onCheckedChange={checked=>void save({knownLanguages:checked?[...known,code]:known.filter(x=>x!==code)})}/>{name}</label>)}</div><p role="status">{status}</p><Accordion type="single" collapsible className="guided-details"><AccordionItem value="details"><AccordionTrigger>Your learning data</AccordionTrigger><AccordionContent><p>We save your account profile, lesson drafts, typed attempts, requested help, review dates and conversations to provide your learning record. Optional AI messages and submitted audio are processed by the configured provider. LingoMitra does not store raw recordings. Check the transcript before sending it as a message; transcription is not a pronunciation assessment.</p><p>Delete your LingoMitra data below to remove these account records. Progress is not sold as a score, and no subscription is required.</p></AccordionContent></AccordionItem></Accordion></section>;
}
